# =====================================================================
# REQUIRED PARAMETERS
# =====================================================================

# Unique key across your SonarQube/SonarCloud instance
sonar.projectKey=Roboshop-catalogue

# =====================================================================
# METADATA & UI SETTINGS (Optional but Recommended)
# =====================================================================

# Name displayed in the SonarQube UI
sonar.projectName=Roboshop-catalogue
sonar.sources=.
sonar.exclusions=**/node_modules/**,Jenkinsfile,Dockerfile